
#                            #
# Allowed Origins         #
#                            #
allowed:
  origins:
    - https://localhost:4200
    - http://127.0.0.1:61522
    - http://127.0.0.1:51186
#                            #
# Server properties          #
#                            #
server:
  port: 4040
  ssl:
    enabled: true # Enable HTTPS support (only accept HTTPS requests)
    key-alias: gibatekpro # Alias that identifies the key in the key store
    key-store: classpath:gibatekpro-keystore.p12 # Keystore location
    key-store-password: secret
    key-store-type: PKCS12 # Keystore format


#                            #
# JDBC connection properties #
#                            #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce?allowPublicKeyRetrieval=True&useSSL=false&serverTimezone=UTC
    username: hbstudent
    password: hbstudent

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    rest:
      base-path: /api
      detection-strategy: ANNOTATED
#                                #
# Security connection properties #
#                                #

okta:
  oauth2:
    client-id: 0oa9bqxt75VG6zKmV5d7
    issuer: https://dev-94498233.okta.com/oauth2/default


#                                #
# Stripe: Payment processing     #
#                                #
stripe:
  key:
    secret: sk_test_51N5XrvG4mCGEpPxu0HkZzBQybI4pnUQnGxFlQzTUMmAwuZyxsyiwiuKezXjY1My1B29nSHWlFLzkXKNPjChgZypl00BO1xhmr0
